### DISCUSSION TITLE
zod creation of required?

### DISCUSSION THREAD

**Discussion by jamalsoueidan** [orval-labs/orval#1028] [General]
```yaml
type: object
properties:
  name:
    type: string
required:
  - "name"
```

Doesn't actually create the required zod? is there something im missing?

```js
export const test = zod.object({
  name: zod.string(),
});
```

I was expecting:
```js
export const test = zod.object({
  name: zod.string().required(),
});
```
