### DISCUSSION TITLE
Handling Default Values in Generated Zod Schemas

### DISCUSSION THREAD

**Discussion by ImEins** [orval-labs/orval#1786] [Q&A]
Hello,

I'm working with an OpenAPI specification and have encountered an issue regarding default values when generating Zod schemas. Here's the scenario:

OpenAPI Definition
In my OpenAPI spec, I have a schema defined as follows:

```yaml
components:
  schemas:
    RandomSchemaName:
      properties:
        random_column:
          type: boolean
          title: Random column
          default: false
```

When generating the Zod schema using Orval, the output looks like this:

```typescript
random_column: zod.boolean().optional()
```

**Expectation**
I was expecting the default value to be included in the generated Zod schema, something like:

```typescript
random_column: zod.boolean().default(false)
```

**My Questions**
1. Is the current behavior expected, or am I missing something in how default values are handled?

2. If this is the expected behavior, would modifying the generateZodValidationSchemaDefinition function like this be the correct approach to include default values?
```typescript
if (schema.default !== undefined) {
  zodSchema.functions.push(['default', schema.default]);
}
```
3. If this isn't implemented yet, I’d be happy to contribute by helping implement this, but I want to ensure that updating only this function would address the issue.

I’d appreciate any guidance or clarification on this matter. Thanks for the fantastic tool!
