### DISCUSSION TITLE
Override generated component schemas

### DISCUSSION THREAD

**Discussion by fjodor-rybakov** [orval-labs/orval#1848] [Q&A]
Hi all! I want to override `export type` or `export interface` in schema generation to `const`. For example:

My schema:
```yml
components:
  schemas:
    InvalidRequestDataException:
      type: object
      properties:
        message:
          type: string
          const: 'Invalid data'
        code:
          type: integer
          const: 1
          description: 'Unique exception code'
      required: [ 'message', 'code' ]
```

What i get now:
```ts
export interface InvalidRequestDataException {
  message: 'Invalid data',
  code: 1
}
```

What i want:
```ts
export const InvalidRequestDataException = {
  message: 'Invalid data',
  code: 1
} as const;
export type InvalidRequestDataExceptionType = typeof InvalidRequestDataException;
```

How i can replace `interface` to `const`?
