### DISCUSSION TITLE
How to let orval fail with exit code 1 when there is a syntax error in the OpenAPI?

### DISCUSSION THREAD

**Discussion by Pallau** [orval-labs/orval#866] [General]
We want to run Orval in a GitLab Pipeline so every time a change was made in an OpenAPI spec Orval should run and build the models, etc. and right away detect any issues with the specs. Thus we have a GitLab Pipeline to do this:

```
verify:
  stage: validate
  script:
    - 'npm i'
    - 'npx orval --config ./orval.config.js'
  artifacts:
    when: always
    paths:
      - src/ 
```
However the Pipeline is always successful despite the fact there are syntax errors:

```
Start orval v6.15.0 - A swagger client generator for typescript
⚠️  SyntaxError: Swagger schema validation failed.
  #/paths/~1disposition/get/parameters/0/schema/type must be equal to one of the allowed values
  #/paths/~1disposition/get/parameters/0/schema must have required property '$ref'
  #/paths/~1disposition/get/parameters/0/schema must match exactly one schema in oneOf
  #/paths/~1disposition/get/parameters/0 must have required property '$ref'
  #/paths/~1disposition/get/parameters/0 must match exactly one schema in oneOf

🎉 dispo-file - Your OpenAPI spec has been converted into ready to use orval!
```
Do you know how to configure the scripts so it fails when there are errors like above? The thing is that the exit code is 0 and not 1 despite the fact there is an SyntaxError.
