### ISSUE TITLE
Zod: readonly fields appears in *CreateBody

### ISSUE THREAD

**Issue by JargeZ** [orval-labs/orval#1548]
## What are the steps to reproduce this issue?

Shema entity example
```yaml
    LegalEntity:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
          maxLength: 255
      required:
      - created_at
      - id
      - name
      - updated_at

```

## What happens?

Generated zod schema for create body have all the fields that marked as readOnly
```js
export const v1OrgstructureLegalEntitiesCreateBody = zod.object({
  "id": zod.string().uuid(),
  "created_at": zod.string().datetime(),
  "updated_at": zod.string().datetime(),
  "name": zod.string().max(v1OrgstructureLegalEntitiesCreateBodyNameMax),
})
```

## What were you expecting to happen?

readonly fields appears only in get-like actions and responses

so it means that CreateBody expected to be
```js
export const v1OrgstructureLegalEntitiesCreateBody = zod.object({
  "name": zod.string().max(v1OrgstructureLegalEntitiesCreateBodyNameMax),
})
```

## What versions are you using?

"orval": "^6.31.0",
"zod": "^3.23.8"
