### ISSUE TITLE
Can't fetch refs from url

### ISSUE THREAD

**Issue by iArranzm** [orval-labs/orval#1557]
Hi! hope you can help me with this.

## What happens?
When I'm trying to generate my services, I'm getting an error when trying to fetch an schema from an URL like this (changed Ref for privacy)
```yaml
properties:
        pet:
          allOf:
            - $ref: "https://raw.githubusercontent.com/orval-labs/orval/master/samples/angular-app/petstore.yaml#/components/schemas/Pet"
            - description: pet info
```
The error is 

> orval --config orval.config.ts
🍻 Start orval v6.31.0 - A swagger client generator for typescript
fakeService: Cleaning output folder
🛑 fakeService - Oops... 🍻. Ref not found: https://raw.githubusercontent.com/orval-labs/orval/master/samples/angular-app/petstore.yaml#/components/schemas/Pet

…

## What were you expecting to happen?
I was expecting that Refs could be retrieved from and URL. At first I thought it was because the URL I was trying to access required me to be connected to the VPN, but when I switch to your test YAML, I get the same error.

## Any other comments?

I'm don't think it's a bug, probably it's a feature not supported or I am doing something wrong.  If you need further info I'll be glad to provide it.

## What versions are you using?

System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 61.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    orval: ^6.31.0 => 6.31.0
