### ISSUE TITLE
Vue Query: Issue with Unref() when GET route has both Path and Query parameters 

### ISSUE THREAD

**Issue by MadManMcIvor** [orval-labs/orval#1711]
## What are the steps to reproduce this issue?

Using react query and fetch
```
client: 'vue-query',
      httpClient: 'fetch',
```

And a GET route with a path param and any number of query params:

```YAML
paths:
  /users/{userId}/orders:
    get:
      summary: Get user orders
      description: Retrieves a list of orders for a specific user with optional filtering
      parameters:
        # Path parameter
        - in: path
          name: userId
          required: true
          schema:
            type: integer
          description: The unique identifier of the user
          example: 12345
        
        # Query parameters
        - in: query
          name: status
          required: false
          schema:
            type: string
            enum: [pending, completed, cancelled]
          description: Filter orders by status
          example: completed
        
        - in: query
          name: fromDate
          required: false
          schema:
            type: string
            format: date
          description: Filter orders from this date (YYYY-MM-DD)
          example: "2024-01-01"
        
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Maximum number of orders to return
```

## What happens?

When going to generate the code, it produces an error when trying to use the Vue's unref() function.

it produces code that incorrectly puts two arguments in the unref() call.

```TS
const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrdersUuid>>
  > = ({ signal }) =>
    getOrderstUuid(unref(ordersUuid, params), {
      signal,
      ...requestOptions,
    });
```

…

## What were you expecting to happen?

I'd expect to have the unref() wrapped separately around both the ordersUuid and the params.
```TS
const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrdersUuid>>
  > = ({ signal }) =>
    getOrderstUuid(unref(ordersUuid), unref(params), {
      signal,
      ...requestOptions,
    });
```

…

## Any logs, error output, etc?
It produces an error relating to calling unref() with two arguments as opposed to just one as required.
…

## Any other comments?
May relate to [issue 1467.](https://github.com/orval-labs/orval/issues/1467)
…

## What versions are you using?
Using 7.2.0 and 7.3.0

Please execute `npx envinfo --system --npmPackages orval,zod,axios,msw,swr,@tanstack/react-query,@tanstack/vue-query,react,vue` and paste the results here.

  System:
    OS: macOS 14.7.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 40.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @tanstack/vue-query: ^5.60.6 => 5.60.6 
    msw: ^2.6.5 => 2.6.5 
    orval: ^7.3.0 => 7.3.0 
    vue: ^3.5.13 => 3.5.13
