### ISSUE TITLE
Schema with type: [<any>, 'null'] and enum is not generated as nullable

### ISSUE THREAD

**Issue by AllieJonsson** [orval-labs/orval#1738]
## What are the steps to reproduce this issue?

Use the following schema:

```yaml
NullStringEnum:
  type:
    - string
    - 'null'
  enum:
    - foo
    - bar
```

## What happens?

Generated code is:
```ts
export type NullStringEnum = typeof NullStringEnum[keyof typeof NullStringEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullStringEnum = {
  foo: 'foo',
  bar: 'bar',
} as const;
```

## What were you expecting to happen?

It should be nullable:
```ts
export type NullStringEnum = typeof NullStringEnum[keyof typeof NullStringEnum] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullStringEnum = {
  foo: 'foo',
  bar: 'bar',
} as const;
```
