### ISSUE TITLE
Support global headers from securitySchemes

### ISSUE THREAD

**Issue by Maxim-Mazurok** [orval-labs/orval#885]
This is related to #465 

However even when using `headers: true` orval doesn't pick up this part of the swagger.json:
```
...
  "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "description": "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter 'Bearer' [space] and then your token in the text input below.\r\n\r\nExample: \"Bearer 1safsfsdfdfd\"",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "Bearer": [ ]
    }
  ]
```

Ideally, I would like to have some sort of global way of setting it up which would be type-safe.

When using openapi-generator we used to pass it into Configuration:

```js
import { Configuration } from "../api/configuration";

export const configuration: Configuration = new Configuration({ basePath: " " });

  configuration.baseOptions = {
    headers: {
      Authorization: "Bearer " + myToken,
    },
  };
```

Later that configuration was used like this:

`const appApi = new AppApi(configuration)`

**Comment by dipsaus9** [comment]
We encounter the same issue. For us this doesn't have to be a global option as it is a security schema, so we should add it like a normal parameter to the generated options.

**Comment by maapteh** [comment]
we have the same, so:

```
  securitySchemes:
    fooAuth:
      type: apiKey
      name: X-Foo
      in: header
      description: 'jaja'
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
 ```
 
 Then on the method:
 ```
   /foo/{bar}/snip:
    post:
      tags: ['Foo']
      summary: 'Foo'
      security:
        - bearerAuth: []
          fooAuth: []
```

Now the bearer is just normal jwt we set it on axios level, but the other option is not possible to be handled over via the hook. At least the option headers: true in the config is not helping me in any way. @melloware did i miss something?
